<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage } from 'element-plus'
type Fingerprint={id:number;canonical_shape:string;occurrence_count:number;mapping_status:string}
const loading=ref(true),error=ref(''),drawer=ref(false),selected=ref<any>(),preview=ref<Record<string,any>>({}),ingestion=ref<any>({}),hooks=ref<any>({}),otel=ref<any>({}),bindings=ref<any[]>([]),fingerprints=ref<Fingerprint[]>([])
const mapping=reactive({type:'$.type',timestamp:'$.timestamp',payloadType:'$.payload.type',turnId:'$.payload.internal_chat_message_metadata_passthrough.turn_id',callId:'$.payload.call_id',role:'$.payload.role',content:'$.payload.content[*].text'})
const labels={type:'外层 type',timestamp:'timestamp',payloadType:'payload.type',turnId:'turn_id',callId:'call_id',role:'role',content:'正文'}
const health=computed(()=>error.value?'异常':hooks.value.pendingJobs?'告警':'就绪')
async function get(url:string,options?:RequestInit){const r=await fetch(url,options);if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
async function load(){loading.value=true;error.value='';try{const[a,h,o,t,u]=await Promise.all([get('/api/ingestion/status'),get('/api/ingestion/hooks/status'),get('/api/ingestion/otel/status'),get('/api/ingestion/transcripts/status'),get('/api/unknown-fingerprints')]);ingestion.value=a;hooks.value=h;otel.value=o;bindings.value=t.items??t;fingerprints.value=u.items}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function rescan(){try{await get('/api/ingestion/rescan',{method:'POST'});await load();ElMessage.success('增量补扫完成')}catch(e){ElMessage.error(String(e))}}
async function edit(item:Fingerprint){selected.value=await get(`/api/unknown-fingerprints/${item.id}`);preview.value={};drawer.value=true}
async function previewMapping(){try{const id=selected.value.fingerprint.id;const result=await get(`/api/unknown-fingerprints/${id}/mapping/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mapping)});preview.value=result.fields}catch(e){ElMessage.error(`预览失败：${e}`)}}
async function save(){try{const id=selected.value.fingerprint.id;await get(`/api/unknown-fingerprints/${id}/mapping`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(mapping)});await get(`/api/unknown-fingerprints/${id}/renormalize`,{method:'POST'});drawer.value=false;await load();ElMessage.success('映射已保存并完成定向重新标准化')}catch(e){ElMessage.error(`映射校验失败：${e}`)}}
onMounted(load)
</script>
<template><main class="page-wrap collection-page" v-loading="loading">
 <section class="hero-row compact-hero"><div><div class="eyebrow">INGESTION HEALTH</div><h1>采集状态</h1><p>全部状态来自本机服务实时 API。</p></div><div class="live-pill"><span class="live-dot"/>{{health}}</div></section>
 <el-alert v-if="error" :title="`无法读取采集服务：${error}`" type="error" :closable="false"/>
 <section class="collector-summary"><article class="panel summary-status"><div><small>Hook 请求</small><b>{{hooks.requests??0}}</b><em>待处理 {{hooks.pendingJobs??0}}</em></div></article><article class="panel summary-status"><div><small>JSONL 原始记录</small><b>{{ingestion.rawRecords??0}}</b><em>{{ingestion.status??'UNKNOWN'}}</em></div></article><article class="panel summary-status"><div><small>UNKNOWN 指纹</small><b>{{fingerprints.length}}</b><em>原样保留</em></div></article><article class="panel summary-status"><div><small>OTLP 对象</small><b>{{(otel.logs?.stored??0)+(otel.traces?.stored??0)+(otel.metrics?.stored??0)}}</b><em>三类信号</em></div></article></section>
 <section class="collection-grid"><div class="collection-main">
  <article class="panel collector-panel"><div class="panel-heading"><div><h2>Hook 接收器</h2><p>HTTP 接收与异步标准化</p></div><el-tag :type="hooks.serverErrors?'danger':'success'">{{hooks.serverErrors?'异常':'监听中'}}</el-tag></div><div class="collector-stats"><div><span>成功</span><b>{{hooks.accepted??0}}</b></div><div><span>重复</span><b>{{hooks.duplicates??0}}</b></div><div><span>P95</span><b>{{hooks.p95ProcessingMs??0}}ms</b></div><div><span>错误</span><b>{{hooks.serverErrors??0}}</b></div></div></article>
  <article class="panel collector-panel"><div class="panel-heading"><div><h2>Transcript 内容补齐</h2><p>路径安全与 session_meta 校验</p></div><el-button @click="rescan">手动增量补扫</el-button></div><el-table :data="bindings" empty-text="尚无绑定"><el-table-column prop="session_id" label="Session"/><el-table-column prop="path_status" label="路径"/><el-table-column prop="session_check_status" label="session_meta"/><el-table-column prop="adapter_version" label="适配器"/></el-table></article>
  <article class="panel collector-panel"><div class="panel-heading"><div><h2>OTLP/HTTP 接收器</h2><p>无实际请求时明确显示 IDLE</p></div></div><el-table :data="Object.entries(otel).map(([signal,value])=>({signal,...(value as object)}))"><el-table-column prop="signal" label="信号"/><el-table-column prop="status" label="状态"/><el-table-column prop="requests" label="请求"/><el-table-column prop="failed" label="失败"/><el-table-column prop="stored" label="保存"/></el-table></article>
 </div><aside class="collection-aside"><article class="panel privacy-panel"><h2>数据边界</h2><ul><li><span class="live-dot"/>仅监听回环地址</li><li><span class="live-dot"/>数据只保存在本机</li><li><span class="live-dot"/>缺失能力显示未知</li></ul></article></aside></section>
 <section class="panel collector-panel unknown-panel" aria-label="UNKNOWN 事件映射"><div class="panel-heading"><div><h2>UNKNOWN 原样保留</h2><p>规范叶子 JSONPath 与值类型</p></div></div><div class="unknown-list"><article v-for="item in fingerprints" :key="item.id"><div><code>fp-{{item.id}}</code><el-tag size="small">{{item.mapping_status}}</el-tag><b>{{item.occurrence_count}} 条</b></div><p>{{item.canonical_shape}}</p><el-button size="small" @click="edit(item)">配置解析</el-button></article><el-empty v-if="!fingerprints.length" description="没有 UNKNOWN 记录"/></div></section>
 <el-drawer v-model="drawer" size="620px" title="UNKNOWN 字段映射"><template v-if="selected"><pre class="raw-sample">{{JSON.stringify(selected.sample,null,2)}}</pre><el-form label-position="top"><el-form-item v-for="(_,field) in mapping" :key="field" :label="labels[field]"><el-input v-model="mapping[field]"/><small v-if="preview[field]" :class="preview[field].error?'mapping-error':'mapping-ok'">{{preview[field].error||`${preview[field].matchCount} 个匹配 · ${preview[field].valueType}`}}</small></el-form-item></el-form><div class="drawer-footer"><span>由服务端执行语法、基数和类型校验。</span><el-button @click="drawer=false">取消</el-button><el-button @click="previewMapping">预览映射</el-button><el-button type="primary" @click="save">保存并重新标准化</el-button></div></template></el-drawer>
</main></template>
