import { expect,test } from '@playwright/test'
import { execFileSync, spawnSync } from 'node:child_process'
import path from 'node:path'
function hook(event:Record<string,unknown>){const result=spawnSync('python3',[path.resolve('../cli/trace_lens_hook.py')],{input:JSON.stringify(event),encoding:'utf8'});expect(result.status).toBe(0);expect(result.stderr).toBe('')}
function resetTestSchema(){const username=process.env.MYSQL_USERNAME;if(!username)throw new Error('MYSQL_USERNAME is required');const base=['--no-defaults','--no-login-paths','--protocol=TCP','--host=127.0.0.1','--port=3306',`--user=${username}`,'--database=codex_analyze_test','--batch','--skip-column-names'];const env={...process.env,MYSQL_PWD:process.env.MYSQL_PASSWORD};const actual=execFileSync('mysql',[...base,'--execute=SELECT DATABASE()'],{env,encoding:'utf8'}).trim();expect(actual).toBe('codex_analyze_test');execFileSync('mysql',[...base,'--execute=DELETE FROM performance_alignment; DELETE FROM raw_otel_object; DELETE FROM unknown_mapping; DELETE FROM unknown_record; DELETE FROM unknown_fingerprint; DELETE FROM jsonl_supplement; DELETE FROM transcript_binding; DELETE FROM normalization_job; DELETE FROM hook_tool_call; DELETE FROM hook_turn; DELETE FROM hook_session; DELETE FROM raw_hook_event; DELETE FROM raw_jsonl_record; DELETE FROM source_file;'],{env,stdio:'pipe'})}
test.beforeAll(async({request})=>{resetTestSchema();const transcript=path.resolve('e2e/fixtures/codex/sessions/e2e.jsonl');const common={session_id:'session-e2e-001',transcript_path:transcript,cwd:'/workspace/demo-project',model:'model-demo',turn_id:'turn-e2e-001'}
 hook({...common,hook_event_name:'UserPromptSubmit',prompt:'真实链路 E2E 测试'})
 hook({...common,hook_event_name:'PreToolUse',tool_use_id:'tool-e2e-001',tool_name:'Bash',tool_input:{command:'synthetic'}})
 hook({...common,hook_event_name:'PostToolUse',tool_use_id:'tool-e2e-001',tool_name:'Bash',tool_response:{exit_code:0}})
 hook({...common,hook_event_name:'Stop',stop_hook_active:false})
 await expect.poll(async()=>{const body=await (await request.get('/api/sessions')).json();return Boolean(body.items.find((item:any)=>item.turn_id==='turn-e2e-001'&&item.ended_at))},{timeout:15_000}).toBe(true)
 const sessions=await (await request.get('/api/sessions')).json();const session=sessions.items.find((item:any)=>item.turn_id==='turn-e2e-001');const start=Number(session.started_at)+1;const end=Math.max(start,Number(session.ended_at)-1)
 const otlp=await request.post('/v1/traces',{data:{resourceSpans:[{scopeSpans:[{spans:[{traceId:'trace-e2e',spanId:'span-e2e',name:'shell',startTimeUnixNano:String(BigInt(start)*1_000_000n),endTimeUnixNano:String(BigInt(end)*1_000_000n),attributes:[{key:'codex.call_id',value:{stringValue:'tool-e2e-001'}}]}]}]}]}});expect(otlp.ok()).toBe(true)
 await expect.poll(async()=>{const body=await (await request.get('/api/sessions/turn-e2e-001/analysis')).json();return body.performanceSpans.length===1&&body.alignments.some((item:any)=>item.level==='EXACT')},{timeout:15_000}).toBe(true)
 await request.post('/api/ingestion/rescan');await expect.poll(async()=>((await request.get('/api/unknown-fingerprints')).json()).then((v:any)=>v.total)).toBeGreaterThan(0)
})
test('真实 Hook 轮次进入对应 Trace 并显示 OTel 证据',async({page,request})=>{await page.goto('/');const row=page.getByRole('row').filter({hasText:'真实链路 E2E 测试'});await expect(row).toBeVisible();await row.click();await expect(page.getByRole('heading',{name:'真实链路 E2E 测试'})).toBeVisible();await expect(page.locator('.trace-title-row .mono').filter({hasText:'turn-e2e-001'})).toBeVisible();await page.getByText(/可访问的时间轴节点列表/).click();const nodes=page.locator('.accessible-node');await expect(nodes.filter({hasText:'PostToolUse'})).toBeVisible();await expect(nodes.filter({hasText:'shell'})).toBeVisible();await expect(page.locator('.alignment-row.exact')).toBeVisible();const body=await (await request.get('/api/sessions/turn-e2e-001/analysis')).json();expect(['modelRequestMs','toolMs','approvalMs','localMs','unattributedMs'].reduce((sum,key)=>sum+Number(body.aggregates[key]),0)).toBe(Number(body.aggregates.totalMs))})
test('真实 UNKNOWN 指纹完成服务端映射',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/采集状态/}).click();const item=page.locator('.unknown-list article').first();await expect(item).toBeVisible();await item.getByRole('button',{name:'配置解析'}).click();await expect(page.getByText('Synthetic UNKNOWN preview')).toBeVisible();await page.getByRole('button',{name:'预览映射'}).click();await expect(page.getByText(/匹配/).first()).toBeVisible();await page.getByRole('button',{name:'保存并重新标准化'}).click();await expect(page.getByText(/映射已保存/)).toBeVisible();await expect(item.getByText('MAPPED')).toBeVisible()})
